### ISSUE TITLE
Upload failures (asteroid, comets, satellites), "The filename, directory name, or volume label syntax is incorrect: ''

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#104]
MW4 0.220.8, connected to the internet as well as over Ethernet to the mount (GM1000HPS, f/w 2.6.12). MW4 can communicate fine with the mount (I can see the position, time and so on). MW4 is installed in a writable location.

I attempted to update the mount with the latest data for satellites, comets/asteroids. MW4 downloads the data and prompts for confirmation ("Should ... database be programmed to the mount?"), then once I click Yes, nothing is displayed. The log reveals errors. The error is repeatable.

The stack trace is below, I will add the log and a preliminary investigation separately. 

```
[2020-12-29 22:28:30.549][C][      loader.py][ 234] Logging an uncatched Exception
[2020-12-29 22:28:30.549][C][      loader.py][ 235] 
[2020-12-29 22:28:30.549][C][      loader.py][ 237] Traceback (most recent call last):
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\gui\mainWmixin\tabSatellite.py", line 674, in progSatellitesFull    suc = self.app.automation.uploadTLEData()
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 467, in uploadTLEData    self.prepareUpdater()
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 296, in prepareUpdater    os.chdir(os.path.dirname(self.installPath))
[2020-12-29 22:28:30.550][C][      loader.py][ 237] OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''


```

**Comment by razvan-astro** [comment]
The application log, with the startup and the attempt to upload the satellite info.

[mw4-2020-12-29.log](https://github.com/mworion/MountWizzard4/files/5752417/mw4-2020-12-29.log)

**Comment by razvan-astro** [comment]
I've also run the Sysinternals Process Monitor to find out what is the problematic path. The file access log (CSV, but Github doesn't allow it directly) is attached. 

Some observations:

- unrelated to the error, MW4 (or, more likely, an underlying library) constantly checks for a file named "@2x" in the current application directory. By constantly I mean every millisecond. The file doesn't exist. Not sure if intentional. 

- the file doesn't show anything unusual with regards to file access (I've used the tool many time). I was hoping I'd see an incorrect path or something, but couldn't. 

If there is anything I can assist with, please let me know.


[mw4 file acces log - satellite (rename as CSV).log](https://github.com/mworion/MountWizzard4/files/5752445/mw4.file.acces.log.-.satellite.rename.as.CSV.log)

**Comment by razvan-astro** [comment]
And here's the similar error for the current comets.
```

2020-12-29 22:28:15.061][U][      loader.py][ 171] Click Tab     : [Satellite]
[2020-12-29 22:28:23.734][U][      loader.py][ 175] Click Button  : [progSatellitesFull]
[2020-12-29 22:28:30.062][U][      loader.py][ 175] Click Button  : []
[2020-12-29 22:28:30.062][U][      loader.py][ 185] Click Object  : [QMessageBoxClassWindow]
[2020-12-29 22:28:30.228][U][      loader.py][ 175] Click Button  : []
[2020-12-29 22:28:30.228][U][      loader.py][ 185] Click Object  : [QMessageBoxClassWindow]
[2020-12-29 22:28:30.235][U][     mainApp.py][ 458] Message window: [Program database:    [Active]]
[2020-12-29 22:28:30.236][U][     mainApp.py][ 458] Message window: [Exporting TLE data]
[2020-12-29 22:28:30.543][U][     mainApp.py][ 458] Message window: [Uploading TLE data to mount]
[2020-12-29 22:28:30.548][C][      loader.py][ 233] 
[2020-12-29 22:28:30.549][C][      loader.py][ 234] Logging an uncatched Exception
[2020-12-29 22:28:30.549][C][      loader.py][ 235] 
[2020-12-29 22:28:30.549][C][      loader.py][ 237] Traceback (most recent call last):
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\gui\mainWmixin\tabSatellite.py", line 674, in progSatellitesFull    suc = self.app.automation.uploadTLEData()
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 467, in uploadTLEData    self.prepareUpdater()
[2020-12-29 22:28:30.549][C][      loader.py][ 237]   File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 296, in prepareUpdater    os.chdir(os.path.dirname(self.installPath))
[2020-12-29 22:28:30.550][C][      loader.py][ 237] OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''
[2020-12-29 22:28:30.550][C][      loader.py][ 239] 
```

**Comment by razvan-astro** [comment]
I looked in a`utomateWindows.py` and I suspect the `os.chdir` is getting an empty string for `self.installPath`. In case the update history matters, I'm attaching the `update.log` file.

[update.log](https://github.com/mworion/MountWizzard4/files/5752466/update.log)

**Comment by razvan-astro** [comment]
Getting closer. I looked in the code to see where `installPath` is taken from (from the registry) but under `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`, I don't see any entry for MW4. Hence the empty string.

**Comment by mworion** [comment]
Hi razvan,
MW4 would be not installed or found in the registry. I'm looking for the original 10micron QCI updater (GmQCIv2.exe) program. 

Do you have installed it on the computer you are using for updating the data? (btw.: I have to add a log entry for this part). The search path is the best where to find it. I you have a setup, where this does not lead to a result, please let me know, I would like to check the registry entry for this to make it more robust. Otherwise I will offer a manual selection method.
Your are using a 64 bit python on your computer, which is for normal running fine. Only point: windows automation with 32bit programs (as the 10micron updater) is or ASCOM drivers does not work nicely), but this is not the current topic.

Last point: I really made a fault: there was no real routing telling the user that the updater was not found ! -> already done now.

If you could walk through the source code (btw: is it readable enough ?) I am missing one entry in the log:
[2020-12-30 09:01:06.046][D][automateWindows][ 102] QCI Updater settings: [(True, '10micron QCI control box updater', 'C:\\Program Files (x86)\\10micron\\Updater\\')]
which should be in in any case, because it has to be logged before you come to the point, where the exception occurs.
the exception is now handled correctly, should not happen in future.

Do you have a software tool in place, which might check if somebody accesses the registry ? And tries to avoid that. 

Michel

**Comment by razvan-astro** [comment]
Hi Michel,

Thanks for your quick reply. I've just updated MW4 with `mw4_update.bat` but did notice that afterwards, the log is still showing  0.220.8.  I have MW4 checked out into a different folder and noticed the changes you made in` automateWindows.py` (in the project) are not reflected in the installation folder at `C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py`

I will include the update.log in case you want to troubleshoot this.  [update.log](https://github.com/mworion/MountWizzard4/files/5754390/update.log)


I overwrote `automateWindows.py` manually and saw the following in the log. There was no message displayed on screen.

```
[2020-12-30 13:57:43.794][U][     mainApp.py][ 458] Message window: [Exporting TLE data]
[2020-12-30 13:57:43.969][U][     mainApp.py][ 458] Message window: [Uploading TLE data to mount]
[2020-12-30 13:57:43.969][E][automateWindows][ 312] No updater found: 
[2020-12-30 13:57:43.969][E][automateWindows][ 493] error'NoneType' object is not subscriptable
[2020-12-30 13:57:43.969][U][     mainApp.py][ 458] Message window: [Uploading error]
[2020-12-30 13:57:43.969][U][     mainApp.py][ 458] Message window: [Programming success]
```

I tried again the updating data in the mount, here are my replies and findings:

I don't run anything that would interfere with registry access.

I do have the 10M updater, in `C:\apps\astro\10micron\Updater\GmQCIv2.exe` and have used it in the past. However, as you suspected, MW is not finding it. I checked the registry entries under `[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall]` and I do have a number of registry entries, I'll add some debugging statements a bit later to see MW is searching for. In the meantime, here's the dump of those registry entries (interestingly, also found 2 pointing to `Program Files (x86)` from when 10M support did some remote troubleshooting on my system.

```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10micron  Client_is1]
"Inno Setup: Setup Version"="5.5.6 (a)"
"Inno Setup: App Path"="C:\\apps\\astro\\10micron\\tle_manager"
"InstallLocation"="C:\\apps\\astro\\10micron\\tle_manager\\"
"Inno Setup: Icon Group"="10micron\\TLE Manager"
"Inno Setup: User"="r"
"Inno Setup: Language"="default"
"DisplayName"="10micron TLE Manager"
"UninstallString"="\"C:\\apps\\astro\\10micron\\tle_manager\\unins000.exe\""
"QuietUninstallString"="\"C:\\apps\\astro\\10micron\\tle_manager\\unins000.exe\" /SILENT"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201102"
"EstimatedSize"=dword:000049c7

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10micron control box updater_is1]
"Inno Setup: Setup Version"="5.6.1 (a)"
"Inno Setup: App Path"="C:\\apps\\astro\\10micron\\Updater"
"InstallLocation"="C:\\apps\\astro\\10micron\\Updater\\"
"Inno Setup: Icon Group"="10micron\\Updater"
"Inno Setup: User"="r"
"Inno Setup: Selected Tasks"="desktopicon"
"Inno Setup: Deselected Tasks"=""
"Inno Setup: Language"="default"
"DisplayName"="10micron control box updater"
"UninstallString"="\"C:\\apps\\astro\\10micron\\Updater\\unins000.exe\""
"QuietUninstallString"="\"C:\\apps\\astro\\10micron\\Updater\\unins000.exe\" /SILENT"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201103"
"EstimatedSize"=dword:00005a4c

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10Micron Mount Configurator_is1]
"Inno Setup: Setup Version"="5.5.6 (a)"
"Inno Setup: App Path"="C:\\apps\\astro\\10micron\\MountConfigurator"
"InstallLocation"="C:\\apps\\astro\\10micron\\MountConfigurator\\"
"Inno Setup: Icon Group"="10micron\\Mount Configurator"
"Inno Setup: User"="r"
"Inno Setup: Selected Tasks"="desktopicon"
"Inno Setup: Deselected Tasks"=""
"Inno Setup: Language"="english"
"DisplayName"="10Micron Mount Configurator 1.0.1.0"
"UninstallString"="\"C:\\Program Files (x86)\\10Micron\\MountConfigurator\\unins000.exe\""
"QuietUninstallString"="\"C:\\Program Files (x86)\\10Micron\\MountConfigurator\\unins000.exe\" /SILENT"
"DisplayVersion"="1.0.1.0"
"Publisher"="COMEC s.n.c."
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201102"
"MajorVersion"=dword:00000001
"MinorVersion"=dword:00000000
"EstimatedSize"=dword:00000923

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10micron Mount Logger_is1]
"Inno Setup: Setup Version"="5.5.6 (a)"
"Inno Setup: App Path"="C:\\apps\\astro\\10micron\\MountLog"
"InstallLocation"="C:\\apps\\astro\\10micron\\MountLog\\"
"Inno Setup: Icon Group"="10micron\\MountLog"
"Inno Setup: User"="r"
"Inno Setup: Selected Tasks"="desktopicon"
"Inno Setup: Deselected Tasks"=""
"Inno Setup: Language"="default"
"DisplayName"="10micron Mount Logger"
"UninstallString"="\"C:\\apps\\astro\\10micron\\MountLog\\unins000.exe\""
"QuietUninstallString"="\"C:\\apps\\astro\\10micron\\MountLog\\unins000.exe\" /SILENT"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201102"
"EstimatedSize"=dword:000007ad

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10micron Mount Remote_is1]
"Inno Setup: Setup Version"="5.5.6 (a)"
"Inno Setup: App Path"="C:\\Program Files (x86)\\10micron\\MountRemote"
"InstallLocation"="C:\\Program Files (x86)\\10micron\\MountRemote\\"
"Inno Setup: Icon Group"="10micron\\MountRemote"
"Inno Setup: User"="r"
"Inno Setup: Language"="default"
"DisplayName"="10micron Mount Remote"
"UninstallString"="\"C:\\Program Files (x86)\\10micron\\MountRemote\\unins000.exe\""
"QuietUninstallString"="\"C:\\Program Files (x86)\\10micron\\MountRemote\\unins000.exe\" /SILENT"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201105"
"EstimatedSize"=dword:000053d8

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\10micron virtual keypad 2_is1]
"Inno Setup: Setup Version"="5.5.6 (a)"
"Inno Setup: App Path"="C:\\apps\\astro\\10micron\\VirtKP2"
"InstallLocation"="C:\\apps\\astro\\10micron\\VirtKP2\\"
"Inno Setup: Icon Group"="10micron\\Virtual Keypad 2"
"Inno Setup: User"="r"
"Inno Setup: Selected Tasks"="desktopicon"
"Inno Setup: Deselected Tasks"=""
"Inno Setup: Language"="default"
"DisplayName"="10micron virtual keypad 2.3"
"UninstallString"="\"C:\\apps\\astro\\10micron\\VirtKP2\\unins000.exe\""
"QuietUninstallString"="\"C:\\apps\\astro\\10micron\\VirtKP2\\unins000.exe\" /SILENT"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"InstallDate"="20201101"
"EstimatedSize"=dword:000007a6

```

I think we are getting really close.

Thanks again for the help,
Razvan

[mw4-2020-12-30.log](https://github.com/mworion/MountWizzard4/files/5754354/mw4-2020-12-30.log)

**Comment by mworion** [comment]
Simple analyse:
your registry has:
"10micron control box updater" and display name for what I search for
mine has:
"10micron QCI control box updater"

this makes the difference. I do not know why, but now I could add this.
if you would like to install the latest (might be risky): open the venv with

venv/Scripts/activate

and do 

pip in install https://github.com/mworion/MountWizzard4/archive/master.zip

it's easier. Next commit it should be improved: 

Michel

**Comment by razvan-astro** [comment]
Hi Michel,

I was just about to enter the same comment :-); I just noticed the same thing and replaced `val = self.getAppSettings('10micron QCI')` with `self.getAppSettings('10micron Updater')` in `__init__` but the result was the same. I'll do a bit more digging then install the latest. 

It's possible that 10M changed their registry key in time, I got the mount just 2 months ago and directly installed the software that came with it.

**Comment by razvan-astro** [comment]
Also tried with `val = self.getAppSettings('10micron control box updater')` but the updater was still not found . Will debug more. Log below in the meantime.

```
[2020-12-30 15:32:02.453][D][     obsSite.py][ 150] Loader dir:[C:\apps\astro\MountWizard4/data]
[2020-12-30 15:32:02.656][I][automateWindows][ 189] getNameKeyFromRegistry - appName = 10micron control box updater
[2020-12-30 15:32:03.265][D][ tabSettMisc.py][ 188] Package Alpha  : ['0.152.0a3', '0.152.0a2', '0.152.0a0', '0.150.26a1', '0.150.25a6', '0.135a4', '0.135a3', '0.135a1', '0.134a5', '0.134a3']
[2020-12-30 15:32:03.265][D][ tabSettMisc.py][ 189] Package Beta   : ['0.220.4b7', '0.220.4b6', '0.220.4b5', '0.220.4b4', '0.220.4b3', '0.220.4b2', '0.220.4b1', '0.220.3b1', '0.190.1b1', '0.190.1b0']
[2020-12-30 15:32:03.265][D][ tabSettMisc.py][ 190] Package Release: ['0.220.8', '0.220.7', '0.220.6', '0.220.5', '0.220.4', '0.220.3', '0.220.2', '0.220.1', '0.220.0', '0.211.0']
[2020-12-30 15:32:04.234][U][     mainApp.py][ 458] Message window: [Enabled device:      [camera]]
[2020-12-30 15:32:04.234][U][     mainApp.py][ 458] Message window: [Enabled device:      [focuser]]
[2020-12-30 15:32:04.234][U][     mainApp.py][ 458] Message window: [Enabled device:      [telescope]]
[2020-12-30 15:32:04.234][I][astrometryASTAP][ 312] ASTAP OK, app:C:\Program Files\astap/astap.exe index:C:\Program Files\astap/*.290
[2020-12-30 15:32:04.234][U][     mainApp.py][ 458] Message window: [ASTROMETRY found:    [ASTAP]]
[2020-12-30 15:32:04.234][U][     mainApp.py][ 458] Message window: [Enabled device:      [astrometry]]
[2020-12-30 15:32:07.916][D][    geometry.py][ 173] using [10micron GM1000HPS] geometry
[2020-12-30 15:32:08.361][U][     mainApp.py][ 458] Message window: [Model names refreshed]
[2020-12-30 15:32:09.358][U][     mainApp.py][ 458] Message window: [Align model data refreshed]
[2020-12-30 15:32:10.504][U][      loader.py][ 173] Click DropDown: [minorPlanetSource]
[2020-12-30 15:32:11.250][U][      loader.py][ 185] Click Object  : []
[2020-12-30 15:32:11.250][U][      loader.py][ 185] Click Object  : [QComboBoxPrivateContainerClassWindow]
[2020-12-30 15:32:11.313][U][      loader.py][ 171] Click Tab     : [Satellite]
[2020-12-30 15:32:12.578][U][      loader.py][ 175] Click Button  : [progSatellitesFull]
[2020-12-30 15:32:13.719][U][      loader.py][ 175] Click Button  : []
[2020-12-30 15:32:13.719][U][      loader.py][ 185] Click Object  : [QMessageBoxClassWindow]
[2020-12-30 15:32:13.812][U][      loader.py][ 175] Click Button  : []
[2020-12-30 15:32:13.812][U][      loader.py][ 185] Click Object  : [QMessageBoxClassWindow]
[2020-12-30 15:32:13.812][U][     mainApp.py][ 458] Message window: [Program database:    [Active]]
[2020-12-30 15:32:13.812][U][     mainApp.py][ 458] Message window: [Exporting TLE data]
[2020-12-30 15:32:14.017][U][     mainApp.py][ 458] Message window: [Uploading TLE data to mount]
[2020-12-30 15:32:14.017][E][automateWindows][ 317] No updater found: 
[2020-12-30 15:32:14.017][E][automateWindows][ 498] error'NoneType' object is not subscriptable
[2020-12-30 15:32:14.017][U][     mainApp.py][ 458] Message window: [Uploading error]
[2020-12-30 15:32:14.017][U][     mainApp.py][ 458] Message window: [Programming success]
[2020-12-30 15:32:14.017][U][      loader.py][ 175] Click Button  : [progSatellitesFull]
```

**Comment by mworion** [comment]
My update was not sufficient. At least to search for the strings.
Have to change a little more. Interesting that the changed string does not find the updater....

**Comment by razvan-astro** [comment]
Give me a few minutes, I'll try yours as well. In the previous test I had merely changed the string in the existing file.

**Comment by razvan-astro** [comment]
OK, I tried updating the direct update. Yeah, it was a bit risky :) It fails to start as it's missing the simulator_ui widget, I think. I'm also attaching the update log for reference.


[mw 0.230.0.log](https://github.com/mworion/MountWizzard4/files/5754736/mw.0.230.0.log)

```
C:\apps\astro\MountWizard4>MW4_Run.bat

C:\apps\astro\MountWizard4>venv\Scripts\activate   && SET QT_SCALE_FACTOR=1.5   && SET QT_FONT_DPI=96   && venv\Scripts\python.exe venv\Lib\site-packages\mw4\loader.py  1>>run.log
Traceback (most recent call last):
  File "venv\Lib\site-packages\mw4\loader.py", line 40, in <module>
    from mainApp import MountWizzard4
  File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\mainApp.py", line 34, in <module>
    from gui.mainWindow.mainW import MainWindow
  File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\gui\mainWindow\mainW.py", line 31, in <module>
    from gui.extWindows.simulatorW import SimulatorWindow
  File "C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\gui\extWindows\simulatorW.py", line 30, in <module>
    from gui.widgets import simulator_ui
ImportError: cannot import name 'simulator_ui' from 'gui.widgets' (C:\apps\astro\MountWizard4\venv\Lib\site-packages\mw4\gui\widgets\__init__.py)
```

**Comment by mworion** [comment]
I think it's better to make a clean beta build for you:

venv/Scripts/activate

and do

pip in install mountwizzard4==0.220.9b1 

Michel

**Comment by mworion** [comment]
Will be off for the next hour+

**Comment by razvan-astro** [comment]
Thanks, I'll be away for the same as well. That tag was not found yet, I'll wait. Appreciate the support!

```
(venv) C:\apps\astro\MountWizard4>pip install mountwizzard4==0.220.9b1
ERROR: Could not find a version that satisfies the requirement mountwizzard4==0.220.9b1
ERROR: No matching distribution found for mountwizzard4==0.220.9b1
```

**Comment by razvan-astro** [comment]
0.220.9b1 is visible now so I updated. This time, the 10M updater was found and started.

The updater didn't work, though; this error must be coming from the 10M updater itself. On the screen there's only a popup box saying it failed. The MW4 log contains more info (see below). I checked the file (`C:\apps\astro\10micron\Updater\satellites.tle`), it exists. I'll try a manual update.  This is a different problem though so you can close this particular ticket.

Thanks!

```
[2020-12-30 17:24:08.589][U][     mainApp.py][ 458] Message window: [Program database:    [Active]]
[2020-12-30 17:24:08.589][U][     mainApp.py][ 458] Message window: [Exporting TLE data]
[2020-12-30 17:24:08.823][U][     mainApp.py][ 458] Message window: [Uploading TLE data to mount]
[2020-12-30 17:24:08.823][I][automateWindows][ 286] Using 64Bit backend uia
[2020-12-30 17:24:33.552][E][automateWindows][ 385] error(-2147220992, None, (None, None, None, 0, None))
[2020-12-30 17:24:33.552][U][     mainApp.py][ 458] Message window: [Uploading error]
[2020-12-30 17:24:33.552][U][     mainApp.py][ 458] Message window: [Programming success]
[2020-12-30 17:24:33.552][U][      loader.py][ 175] Click Button  : [progSatellitesFull]



```

**Comment by razvan-astro** [comment]
And some final comments. Updating comets and asteroids works. Updating satellites doesn't but it fails also when using the 10M Updater directly. `satellites.tle` looks ok inside (i.e. no data corruption) so I'll follow-up with 10M support in the new year.

**Comment by razvan-astro** [comment]
And just in case there's a problem with `satellites.tle`, for the record, it's attached.
[satellites.zip](https://github.com/mworion/MountWizzard4/files/5755124/satellites.zip)

**Comment by mworion** [comment]
Razvan,

for the satellites I would use the functionality of MW4 directly. You don't need the updated for a selected satellite to be programmed. This could be done via the command protocol directly.

Michel

**Comment by razvan-astro** [comment]
Got it, thanks! This one worked correctly.
