### ISSUE TITLE
automated update of TLE, Earth rotation, satellites does not work in 2.0.1 but in previous betas

### ISSUE THREAD

**Issue by drone1de** [mworion/MountWizzard4#175]
Recently installed 2.0.1 on a new computer. Recognized that updating of TLE files or earth rotation or any other file with the automation script (using 10µ updater tool) does not work.
On another computer I was running the latest beta and 1.0.7 and it worked in both versions. I then updated here to 2.0.1 and the functionality got lost here as well. 

Both computer run Windows 10 pro, latest updates installed.

Best regards,
Lars

[2021-08-30 16:57:02.839][H][      loader.py][ 277] ----------------------------------------------------------------------------------------------------
[2021-08-30 16:57:02.839][H][      loader.py][ 278] mountwizzard4    : 2.0.1
[2021-08-30 16:57:02.839][H][      loader.py][ 279] platform         : Windows
[2021-08-30 16:57:02.839][H][      loader.py][ 280] sys.executable   : C:\DATA\MW4\venv\Scripts\python.exe
[2021-08-30 16:57:02.839][H][      loader.py][ 281] actual workdir   : C:\DATA\MW4
[2021-08-30 16:57:02.839][H][      loader.py][ 282] machine          : AMD64
[2021-08-30 16:57:02.839][H][      loader.py][ 283] cpu              : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
[2021-08-30 16:57:02.850][H][      loader.py][ 284] release          : 10
[2021-08-30 16:57:02.850][H][      loader.py][ 285] python           : 3.9.2
[2021-08-30 16:57:02.850][H][      loader.py][ 286] python runtime   : 32bit
[2021-08-30 16:57:02.850][H][      loader.py][ 287] PyQt5 / Qt       : 5.15.4 / 5.15.2
[2021-08-30 16:57:02.850][H][      loader.py][ 288] node / hostname  : LAPTOP-AS5G5CN8 / LAPTOP-AS5G5CN8
[2021-08-30 16:57:02.850][H][      loader.py][ 289] ----------------------------------------------------------------------------------------------------
[2021-08-30 16:57:02.877][D][      loader.py][ 338] Writing file:  [de421_23.bsp]
[2021-08-30 16:57:02.889][D][      loader.py][ 338] Writing file:  [active.txt]
[2021-08-30 16:57:02.900][D][      loader.py][ 338] Writing file:  [CDFLeapSeconds.txt]
[2021-08-30 16:57:02.938][D][      loader.py][ 338] Writing file:  [finals2000A.all]
[2021-08-30 16:57:02.970][D][      loader.py][ 338] Writing file:  [finals.data]
[2021-08-30 16:57:03.015][I][     mainApp.py][ 336] Config file C:\DATA\MW4/config/config.cfg not existing
[2021-08-30 16:57:03.219][I][     obsSite.py][ 139] Timescale is using downloaded version
[2021-08-30 16:57:06.564][I][       mount.py][ 137] wrong MAC value: 
[2021-08-30 16:57:10.939][U][      loader.py][ 169] Click Tab     : [Settings]
[2021-08-30 16:57:13.760][U][      loader.py][ 169] Click Tab     : [Mount]
[2021-08-30 16:57:14.914][U][      loader.py][ 178] Click Group   : [groupBox_62], value: [True]
[2021-08-30 16:57:15.605][U][      loader.py][ 184] Click EditLine: [mountHost]:
[2021-08-30 16:57:27.840][U][     mainApp.py][ 413] Message window: [Model names refreshed]
[2021-08-30 16:57:31.134][U][     mainApp.py][ 413] Message window: [Align model data refreshed]
[2021-08-30 16:57:32.961][U][      loader.py][ 169] Click Tab     : [Tools]
[2021-08-30 16:57:41.947][U][      loader.py][ 169] Click Tab     : [Update / Time / Audio / Misc]
[2021-08-30 16:57:43.371][U][      loader.py][ 181] Click Checkbox: [isOnline], value: [True]
[2021-08-30 16:57:51.933][U][      loader.py][ 169] Click Tab     : [Tools]
[2021-08-30 16:57:58.018][U][      loader.py][ 173] Click Button  : [progEarthRotationData]
[2021-08-30 16:57:59.812][U][      loader.py][ 173] Click Button  : []
[2021-08-30 16:57:59.812][U][      loader.py][ 186] Click Object  : [QMessageBoxClassWindow]
[2021-08-30 16:58:00.031][U][      loader.py][ 173] Click Button  : []
[2021-08-30 16:58:00.031][U][      loader.py][ 186] Click Object  : [QMessageBoxClassWindow]
[2021-08-30 16:58:00.041][U][     mainApp.py][ 413] Message window: [Program to mount:    [earth rotation data]]
[2021-08-30 16:58:00.042][U][     mainApp.py][ 413] Message window: [Writing files: finals.data, tai-utc.dat]
[2021-08-30 16:58:00.071][U][     mainApp.py][ 413] Message window: [Uploading IERS data to mount]
[2021-08-30 16:58:00.072][I][automateWindows][ 279] Using 32Bit backend win32
[2021-08-30 16:58:00.832][C][      loader.py][ 233] 
[2021-08-30 16:58:00.832][C][      loader.py][ 234] Logging an uncatched Exception
[2021-08-30 16:58:00.832][C][      loader.py][ 235] 
[2021-08-30 16:58:00.833][C][      loader.py][ 237] Traceback (most recent call last):
[2021-08-30 16:58:00.833][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 256, in checkFloatingPointErrorWindow    dialog = timings.wait_until_passes(2,
[2021-08-30 16:58:00.833][C][      loader.py][ 237] NameError: name 'timings' is not defined
[2021-08-30 16:58:00.833][C][      loader.py][ 237] During handling of the above exception, another exception occurred:
[2021-08-30 16:58:00.833][C][      loader.py][ 237] Traceback (most recent call last):
[2021-08-30 16:58:00.833][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\gui\mainWmixin\tabMinorPlanetTime.py", line 241, in progEarthRotationDataToMount    suc = self.app.automation.uploadEarthRotationData()
[2021-08-30 16:58:00.833][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 486, in uploadEarthRotationData    self.prepareUpdater()
[2021-08-30 16:58:00.834][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 340, in prepareUpdater    suc = self.startUpdater()
[2021-08-30 16:58:00.834][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 299, in startUpdater    suc = self.checkFloatingPointErrorWindow()
[2021-08-30 16:58:00.834][C][      loader.py][ 237]   File "C:\DATA\MW4\venv\Lib\site-packages\mw4\logic\automation\automateWindows.py", line 263, in checkFloatingPointErrorWindow    except timings.TimeoutError:
[2021-08-30 16:58:00.834][C][      loader.py][ 237] NameError: name 'timings' is not defined
[2021-08-30 16:58:00.834][C][      loader.py][ 239] 
[2021-08-30 16:58:00.840][U][      loader.py][ 173] Click Button  : [progEarthRotationData]
[2021-08-30 16:58:08.002][U][      loader.py][ 173] Click Button  : [openMessageW]
[2021-08-30 16:58:15.286][U][      loader.py][ 186] Click Object  : [MessageDialog]
[2021-08-30 16:58:15.286][U][      loader.py][ 186] Click Object  : [MessageDialogWindow]
[2021-08-30 16:58:15.516][U][      loader.py][ 186] Click Object  : [MainWindow]
[2021-08-30 16:58:26.021][U][     mainApp.py][ 413] Message window: [MountWizzard4 manual stopped]

**Comment by mworion** [comment]
Hi Lars,
sorry to hear. Would you mind to post the full log as file? As I scan the log for various entries this would help me a lot. 
Something is different in you systems as my test worked out fine. The log shows that a library is not installed which is in any case very suspicious.
Thanks for your help.
Michel

**Comment by drone1de** [comment]
[install.log](https://github.com/mworion/MountWizzard4/files/7082452/install.log)
[mw4-2021-08-30.log](https://github.com/mworion/MountWizzard4/files/7082453/mw4-2021-08-30.log)
[run.log](https://github.com/mworion/MountWizzard4/files/7082454/run.log)

Hi Michael, logs attached, 
Grüße,
Lars

**Comment by mworion** [comment]
Lars,
helped. One step further: could you enable log level debug (under settings/misc), make another try and post the log as well ? Many thanks.
Michel

**Comment by drone1de** [comment]
[mw4-2021-08-31.log](https://github.com/mworion/MountWizzard4/files/7083465/mw4-2021-08-31.log)
[run.log](https://github.com/mworion/MountWizzard4/files/7083466/run.log)

Bitteschön!

Thanks Michael!

**Comment by drone1de** [comment]
[mw4-2021-08-31.log](https://github.com/mworion/MountWizzard4/files/7083630/mw4-2021-08-31.log)
[run.log](https://github.com/mworion/MountWizzard4/files/7083631/run.log)

and here with "trace" instead of "debug"

Cheers,
Lars

**Comment by mworion** [comment]
Just to be clear. The latest betas like v2.0.0b44 did work, correct ?

**Comment by drone1de** [comment]
correct, 2.0betas and 1.0.7 worked as intended, b44 included

**Comment by mworion** [comment]
Lars,
strange as I did not change things there. If you could test v2.0.0 as well as it should be identical to v2.0.0b44.
Michel

**Comment by drone1de** [comment]
Hi Michel,
can confirm: downgrade to 2.0.0.b44 performed, restarted, earth rotation data update: worked like a charme
upgrade to release 2.0.1: earth rotation data gets stuck.
maybe to clarify: the 10µ updater program starts as it should but then no automated clicking does occur anymore. With beta 2.0.0.b44 it continued.
Grüße,
Lars

**Comment by drone1de** [comment]
Michel, my guess is the automation scripts ... are there new libs coming from beta to release version?

**Comment by drone1de** [comment]
overlooked the fix....2.0.2b1 is working as it should, FIXED!!!
Thanks Michel!!!

**Comment by mworion** [comment]
OK, good to hear.
No, there were no updates. It's for some reason an import error for the used library. No clue why this happens,
Michel
