### ISSUE TITLE
No config.cfg file

### ISSUE THREAD

**Issue by jeffweiss2131** [mworion/MountWizzard4#285]
**Describe the bug**
Each time I try and install MW4 on my Alienware laptop running win 11, it will not work. I see the small blue mw4 square for a few seconds, then I see the larger white rectangle for a few seconds then it all disappears. When I look at the logs, all I can see is that there is no work\config\config.cfg file.

This exact same thing happens on my Alienware desktop machine. 

**To Reproduce**
1. Go to 'Setup.pyz script
5. [2022-12-14 17:36:08.677][I][      loader.py][ 333] Using existing: [mountwizzard4.pdf]
[2022-12-14 17:36:08.682][I][     profile.py][ 190] Config file C:\Users\jeffw\Desktop\Work/config/config.cfg not existing
[2022-12-14 17:36:08.758][I][     obsSite.py][ 141] Timescale is using downloaded version

[2022-12-14 09:36:06.798][I][    startup.pyz][ 135] [STDOUT] ...starting
[2022-12-14 09:36:12.818][D][    startup.pyz][  66] Exit code:[3221225477], message:[], success:[False]
[2022-12-14 09:36:12.818][I][    startup.pyz][ 135] [STDOUT] ...failed to start MW4
[2022-12-14 09:36:12.818][I][    startup.pyz][ 135] [STDOUT] Closing application

**Expected behavior**

Program should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Wiin 11
 - Browser Chrome
 

**Smartphone (please complete the following information):**

**Additional context**
I have two powerful Alienware computers running win 11 and now I cannot get MW4 to work.

**Comment by jeffweiss2131** [comment]
[mw4-2022-12-14.log](https://github.com/mworion/MountWizzard4/files/10230402/mw4-2022-12-14.log)

**Comment by jeffweiss2131** [comment]
[startup-2022-12-14.log](https://github.com/mworion/MountWizzard4/files/10230405/startup-2022-12-14.log)

**Comment by mworion** [comment]
Hi Jeff, could you post the config file? You need to zip it before dragging it here.

**Comment by jeffweiss2131** [comment]
There was no config.cfg file in the work/config directory. 
If I make one and put a 0 in row 1 column 1, the startup script dos make it a few steps further. 

The problem is that after running the startup.pyz script, there is no config.cfg file.

This is the log after a brand new innstall and running startup.pyz.
There is no config.cfg file in the config folder.

[2022-12-15 17:52:19.781][H][      loader.py][ 308] ----------------------------------------------------------------------------------------------------
[2022-12-15 17:52:19.783][H][      loader.py][ 309] mountwizzard4    : 2.2.8
[2022-12-15 17:52:19.783][H][      loader.py][ 310] platform         : Windows
[2022-12-15 17:52:19.783][H][      loader.py][ 311] sys.executable   : C:\Users\jeffw\Desktop\Work\venv\Scripts\python.exe
[2022-12-15 17:52:19.783][H][      loader.py][ 312] actual workdir   : C:\Users\jeffw\Desktop\Work
[2022-12-15 17:52:19.783][H][      loader.py][ 313] machine          : AMD64
[2022-12-15 17:52:19.784][H][      loader.py][ 314] cpu              : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
[2022-12-15 17:52:19.784][H][      loader.py][ 315] release          : 10
[2022-12-15 17:52:19.784][H][      loader.py][ 316] python           : 3.9.0
[2022-12-15 17:52:19.784][H][      loader.py][ 317] python runtime   : 64bit
[2022-12-15 17:52:19.784][H][      loader.py][ 318] PyQt5 / Qt       : 5.15.4 / 5.15.2
[2022-12-15 17:52:19.784][H][      loader.py][ 319] node / hostname  : AstroAlien / AstroAlien
[2022-12-15 17:52:19.784][H][      loader.py][ 320] run as admin     : no
[2022-12-15 17:52:19.784][H][      loader.py][ 321] ----------------------------------------------------------------------------------------------------
[2022-12-15 17:52:19.789][I][      loader.py][ 344] Using existing: [de421_23.bsp]
[2022-12-15 17:52:19.792][I][      loader.py][ 344] Using existing: [visual.txt]
[2022-12-15 17:52:19.795][I][      loader.py][ 344] Using existing: [CDFLeapSeconds.txt]
[2022-12-15 17:52:19.796][I][      loader.py][ 344] Using existing: [tai-utc.dat]
[2022-12-15 17:52:19.798][I][      loader.py][ 344] Using existing: [finals2000A.all]
[2022-12-15 17:52:19.813][I][      loader.py][ 344] Using existing: [finals.data]
[2022-12-15 17:52:19.836][I][     mainApp.py][ 339] Config file C:\Users\jeffw\Desktop\Work/config/config.cfg not existing
[2022-12-15 17:52:19.894][I][     obsSite.py][ 141] Timescale is using downloaded version
[2022-12-15 17:52:19.913][U][     mainApp.py][ 416] Message window: [10micron updater:    [C:\Program Files (x86)\10micron\Updater\GmQCIv2.exe]]
[2022-12-15 17:52:21.136][I][       mount.py][ 137] wrong MAC value:

**Comment by jeffweiss2131** [comment]
If I create a config.cfg file and place it in the config folder with a 0 in row 1 column 1 I get a different error.

After running startup.pyz again and placing a config.cfg file in the config folder,  I get this different error.

[2022-12-15 17:56:53.789][H][      loader.py][ 308] ----------------------------------------------------------------------------------------------------
[2022-12-15 17:56:53.791][H][      loader.py][ 309] mountwizzard4    : 2.2.8
[2022-12-15 17:56:53.791][H][      loader.py][ 310] platform         : Windows
[2022-12-15 17:56:53.791][H][      loader.py][ 311] sys.executable   : C:\Users\jeffw\Desktop\Work\venv\Scripts\python.exe
[2022-12-15 17:56:53.791][H][      loader.py][ 312] actual workdir   : C:\Users\jeffw\Desktop\Work
[2022-12-15 17:56:53.791][H][      loader.py][ 313] machine          : AMD64
[2022-12-15 17:56:53.791][H][      loader.py][ 314] cpu              : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
[2022-12-15 17:56:53.791][H][      loader.py][ 315] release          : 10
[2022-12-15 17:56:53.791][H][      loader.py][ 316] python           : 3.9.0
[2022-12-15 17:56:53.791][H][      loader.py][ 317] python runtime   : 64bit
[2022-12-15 17:56:53.791][H][      loader.py][ 318] PyQt5 / Qt       : 5.15.4 / 5.15.2
[2022-12-15 17:56:53.791][H][      loader.py][ 319] node / hostname  : AstroAlien / AstroAlien
[2022-12-15 17:56:53.791][H][      loader.py][ 320] run as admin     : no
[2022-12-15 17:56:53.792][H][      loader.py][ 321] ----------------------------------------------------------------------------------------------------
[2022-12-15 17:56:53.797][I][      loader.py][ 344] Using existing: [de421_23.bsp]
[2022-12-15 17:56:53.798][I][      loader.py][ 344] Using existing: [visual.txt]
[2022-12-15 17:56:53.800][I][      loader.py][ 344] Using existing: [CDFLeapSeconds.txt]
[2022-12-15 17:56:53.801][I][      loader.py][ 344] Using existing: [tai-utc.dat]
[2022-12-15 17:56:53.802][I][      loader.py][ 344] Using existing: [finals2000A.all]
[2022-12-15 17:56:53.803][I][      loader.py][ 344] Using existing: [finals.data]
[2022-12-15 17:56:53.808][C][      loader.py][ 239] 
[2022-12-15 17:56:53.808][C][      loader.py][ 240] Logging an uncatched Exception
[2022-12-15 17:56:53.808][C][      loader.py][ 241] 
[2022-12-15 17:56:53.808][C][      loader.py][ 243] Traceback (most recent call last):
[2022-12-15 17:56:53.808][C][      loader.py][ 243]   File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\loader.py", line 469, in <module>    main()
[2022-12-15 17:56:53.808][C][      loader.py][ 243]   File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\loader.py", line 460, in main    MountWizzard4(mwGlob=mwGlob, application=app)
[2022-12-15 17:56:53.808][C][      loader.py][ 243]   File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\mainApp.py", line 135, in __init__    profile = self.config.get('profileName', '-')
[2022-12-15 17:56:53.808][C][      loader.py][ 243] AttributeError: 'int' object has no attribute 'get'
[2022-12-15 17:56:53.809][C][      loader.py][ 245] 
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] Traceback (most recent call last):
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\loader.py", line 469, in <module>
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] main()
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\loader.py", line 460, in main
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] MountWizzard4(mwGlob=mwGlob, application=app)
[2022-12-15 17:56:53.809][E][    loggerMW.py][  43] [STDERR] File "C:\Users\jeffw\Desktop\Work\venv\lib\site-packages\mw4\mainApp.py", line 135, in __init__
[2022-12-15 17:56:53.810][E][    loggerMW.py][  43] [STDERR] profile = self.config.get('profileName', '-')
[2022-12-15 17:56:53.810][E][    loggerMW.py][  43] [STDERR] AttributeError
[2022-12-15 17:56:53.810][E][    loggerMW.py][  43] [STDERR] :
[2022-12-15 17:56:53.810][E][    loggerMW.py][  43] [STDERR] 'int' object has no attribute 'get'

**Comment by jeffweiss2131** [comment]
I need a correct config file to be created in the correct location when I install the software.

**Comment by mworion** [comment]
Hi Jeff, 
that's a really strange one. 
Some remarks:
You do not need any config as it should be created automatically. 
Even if you have a defect version it will be corrected to default.
Your last try is with version 2.2.8 whereas your first reports leads to v3.0.4beta. Both have different configs. v3 could upgrade from v2.x but not the other way round.
The error code I see is a windows error code telling access violation. 
Suspecting that there were no writing rights in this folder. This is usually true for any default windows installation since win10.
Would you mind checking this and report back. Before starting MW4 again, please delete "config.cfg" and "profile" 
I have seen a crash with a white window once (but not with this widows error code), but without any trace entries during the last 2 years.
Michel

**Comment by jeffweiss2131** [comment]
This is the log when I remove the config.cfg.

The application is looking for the config.cfg.

I was unable to find a profile file.

As far as I can tell, I have rights to write in the folder. I created a
config.cfg file and placed it there.

**Comment by jeffweiss2131** [comment]
Why is this the link for the windows startup script?

It does not work.

https://github.com/mworion/MountWizzard4/blob/master/support/Windows_Scripts.zip

https://mountwizzard4.readthedocs.io/en/latest/install/mw4.html
This page takes you to that link when you try and install MountWizard4 on
Windows.

What is the proper startup script for installing Mount Wizard on windows 11?

**Comment by ACMBakx** [comment]
I can concurrr.
After a fresh installation on a new PC (Mele3Q) is see the same behavior.
The MW logo shows. A white empty square is shown and all disappears.
This is 2.2.8. Latest Python and install script V3.

**Comment by jeffweiss2131** [comment]
With the exact same install process, My Alienware Desktop now successfully runs MW4. My Alienware laptop, nos to lucky.

Python 3.9.13 

Blue MW4 square for a few seconds, white rectangle for a few seconds then nothing.

**Comment by jeffweiss2131** [comment]
--------------------------------------------------
MountWizzard4
--------------------------------------------------
script version   : 3.0beta6
platform         : Windows
machine          : AMD64
python           : 3.9.13
--------------------------------------------------
Activate virtual environment

MountWizzard4 present

MountWizzard4 is ready
...starting

**Comment by ACMBakx** [comment]
Tried once more today.
Reinstalled Python 3.9.7
This time WITH "add path" checked.
Same result. Logo + white square.
Then nothing.
[mw4-2022-12-28.log](https://github.com/mworion/MountWizzard4/files/10313747/mw4-2022-12-28.log)
[startup-2022-12-28.log](https://github.com/mworion/MountWizzard4/files/10313748/startup-2022-12-28.log)

**Comment by mworion** [comment]
Is there any difference now with beta9 (which should address this issue ?)

**Comment by jeffweiss2131** [comment]
I will try again later today and get back to you/

**Comment by jeffweiss2131** [comment]
I was unable to find the beta9. When I tried the beta8 version, it failed once again.

Can you send ma a link to the beta9 script?

Thank you
Jeff

**Comment by jeffweiss2131** [comment]
I was unable to find the beta9 version of the script.

Jeff

**Comment by mworion** [comment]
Hi Jeff,

Use the latest script, but use the latest beta from MW4 as there might be conflicts in some window version about paths, which should be cleaned now.
Sorry for being unclear.

Michel

> Am 15.01.2023 um 19:46 schrieb Jeff Weiss ***@***.***>:
> 
> 
> I was unable to find the beta9 version of the script.
> 
> Jeff
>

**Comment by jeffweiss2131** [comment]
I do not know how to locate the beta9 version of MW4. I just create a
folder on my desktop named "Workdir" and I place the 4 files from the
startup.zip in that folder and I double click startup.py.

How do I use the beta version of MW4?

Jeff

**Comment by mworion** [comment]
Jeff,
normally the script installs the latest official version, you could go for beta either:
- having v2 installed, go online, check beta in the internal updater and update (take some time)
- pit the files in an empty work folder and run the startup.pyz script with parameters. There you could select --help to see all or use --update-beta to go for latest beta.
Hope this helps
