### ISSUE TITLE
Regression on Mac with latest version, not launching

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#50]
I was running fine, then updated to the latest version, now I get these messages in the console when trying to launch MW4.

Traceback (most recent call last):
  File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 44, in <module>
    from mw4.mainApp import MountWizzard4
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/mw4/mainApp.py", line 28, in <module>
    from mountcontrol import qtmount
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/mountcontrol/qtmount.py", line 31, in <module>
    import mountcontrol.mount
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/mountcontrol/mount.py", line 29, in <module>
    from mountcontrol.firmware import Firmware
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/mountcontrol/firmware.py", line 27, in <module>
    from mountcontrol.convert import valueToInt
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/mountcontrol/convert.py", line 26, in <module>
    import skyfield.api
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/skyfield/api.py", line 13, in <module>
    from .iokit import Loader, load_file
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/skyfield/iokit.py", line 17, in <module>
    from .jpllib import SpiceKernel
  File "/Users/andrewburwell/mw4/venv/lib/python3.7/site-packages/skyfield/jpllib.py", line 6, in <module>
    from jplephem.exceptions import OutOfRangeError
ModuleNotFoundError: No module named 'jplephem.exceptions'

**Comment by Raddock** [comment]
Here's the last log, I upgraded at the end of the session, so it should be the last thing.
[mw4-2020-06-12.log.zip](https://github.com/mworion/MountWizzard4/files/4774843/mw4-2020-06-12.log.zip)

**Comment by mworion** [comment]
Sorry about this,
it‘s an issue of an external used library. This issue is fixed in this library and MW4 will reference this with 0.150.25 which will be available today.
Meanwhile you could solve the issue if you update this library manually. Open a terminal, change to the working directory and do the following commands:

source ./venv/bin/acitvate
pip install jplephem --upgrade
deactivate

After that, MW will start without changes.

Michel

PS: As recommendation as long as I can‘t offer a stable official release it might make sense to keep a working copy of MW4 by just copying the complete work folder and test beta upgrades before loosing a running environment.

**Comment by Raddock** [comment]
Thanks for the fix. I had not considered running a separate copy for updates and I'll do that going forward.
