### ISSUE TITLE
MW4 not starting after update (ModuleNotFoundError: No module named 'sgp4.exporter')

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#59]
Hi Michel,

actually I am faced with the issue, that MW4 will not start anymore on my Ubuntu 18.04 system.
After updating MW4 to most resent version using the internal update functionality, MW4 is not starting anymore.
If I start on console I can see:
 ./MW4_Run.sh 
Traceback (most recent call last):
  File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 44, in <module>
    from mw4.mainApp import MountWizzard4
  File "/home/lux/MountWizzard4/venv/lib/python3.7/site-packages/mw4/mainApp.py", line 34, in <module>
    from mw4.gui.mainW import MainWindow
  File "/home/lux/MountWizzard4/venv/lib/python3.7/site-packages/mw4/gui/mainW.py", line 55, in <module>
    from mw4.gui.mainWmixin.tabSatellite import Satellite
  File "/home/lux/MountWizzard4/venv/lib/python3.7/site-packages/mw4/gui/mainWmixin/tabSatellite.py", line 24, in <module>
    from sgp4.exporter import export_tle
ModuleNotFoundError: No module named 'sgp4.exporter'

I tried to fix it with an manual Update using MW4_Update.sh -- no success.
I installed " sudo apt install python-sgp4" -- no success.

Do you have an idea, what could be wrong ?

Kind regards,
Kay.

**Comment by mworion** [comment]
Kay,

first shot just without checking in detail: 
enable venv from work dir: 
source venv/bin/activate
then
pip install sgp4 —upgrade

hope this works

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
I did 
source venv/bin/activate
then
pip install sgp4 —upgrade

and after that I got:
./MW4_Run.sh
Traceback (most recent call last):
  File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 30, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

After that I restarted the Update again with:
./MW4_Update.sh

After that MW4 is working again.
Thank you for your very quick support.

Kay

**Comment by mworion** [comment]
OK Closing Issue

**Comment by mworion** [comment]
2nd try
